# Generated by Django 3.2.15 on 2025-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('gas_rate_fact', models.FloatField()),
                ('gas_rate_plan', models.FloatField()),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
