# Generated by Django 5.2.1 on 2025-05-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasrecord',
            name='gas_rate_v1',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate V1'),
        ),
        migrations.AddField(
            model_name='gasrecord',
            name='gas_rate_v2',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate V2'),
        ),
        migrations.AddField(
            model_name='gasrecord',
            name='gas_rate_v3',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate V3'),
        ),
    ]
