# Generated by Django 5.2.1 on 2025-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_annotation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrecord',
            name='gas_rate_fact',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
